---
  apiVersion: eksctl.io/v1alpha5
  kind: ClusterConfig
  
  metadata:
    name: eks-gitops
    region: us-east-1
    version: '1.20'  
  availabilityZones: 
      - us-east-1f
      - us-east-1b
  managedNodeGroups:
    - name: linux-ng
      instanceType: t3.large
      minSize: 2
  
  vpc:
      cidr: 172.31.0.0/16